# Site settings
title: Desarrollo web sensible # Title of your site
description: > # this means to ignore newlines until "baseurl:"
  Alex Vicente
cover: image-10.jpg #header.jpg
logo: logo100.png
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /:title # Permalink structure
url: "http://alexvijo.github.io" # "http://localhost:4000"# the base hostname & protocol for your site
paginate: 5 # Number of posts per page
paginate_path: page/:num #Permalink structure for pagination

author: # You can invoke these via {{ site.author.NAME }} 
    name: Alex Vicente # Change to your name
    gravatar: https://secure.gravatar.com/avatar/45cb3c20d3ef766381f3720e29775f44?s=100
    bio: >
        Hello world! This is a short bio of who I am, what I'm doing and how awesome I am. # Short and sweet about you
    location: Barcelona # Where you live (accuracy not guaranteed)
    home: http://alexvijo.github.io/ # Your website, must include http:// otherwise Jekyll thinks it's an internal link

# Build settings
markdown: kramdown
